// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4eP0sCXoO7v888iubuRicK1dVPoTCuw',
    appId: '1:148665146396:web:351611d19bda9b00a293d9',
    messagingSenderId: '148665146396',
    projectId: 'nas-shop',
    authDomain: 'nas-shop.firebaseapp.com',
    storageBucket: 'nas-shop.firebasestorage.app',
    measurementId: 'G-B3F73E483X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3g-sxqru3AUpU7XwHM6EBM4FNqpTuUrw',
    appId: '1:148665146396:android:aaa421d771d8023ba293d9',
    messagingSenderId: '148665146396',
    projectId: 'nas-shop',
    storageBucket: 'nas-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8tYuQOWC2R3-OOlm6X5d6WfxMoiSKssA',
    appId: '1:148665146396:ios:3019504c3b1a5885a293d9',
    messagingSenderId: '148665146396',
    projectId: 'nas-shop',
    storageBucket: 'nas-shop.firebasestorage.app',
    iosClientId:
        '148665146396-a2r621ol53me3t6lfjucgnqb200rv5q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8tYuQOWC2R3-OOlm6X5d6WfxMoiSKssA',
    appId: '1:148665146396:ios:3019504c3b1a5885a293d9',
    messagingSenderId: '148665146396',
    projectId: 'nas-shop',
    storageBucket: 'nas-shop.firebasestorage.app',
    iosClientId:
        '148665146396-a2r621ol53me3t6lfjucgnqb200rv5q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4eKUXj2afq-2DDfMDN0gnew0elJhHMKo',
    appId: '1:148665146396:web:0df53db0a89f767da293d9',
    messagingSenderId: '148665146396',
    projectId: 'nas-shop',
    authDomain: 'nas-shop.firebaseapp.com',
    storageBucket: 'nas-shop.firebasestorage.app',
    measurementId: 'G-BLGY1DDC15',
  );
}
